services:
  web:
    build: .
    ports:
      - "8007:8000"
    tty: true
    working_dir: /app/djangoproject
    command:
      - /bin/sh
      - -c
      - |
        export admin_username=${DJANGO_ADMIN_USERNAME}
        export admin_password=${DJANGO_ADMIN_PASSWORD}
        python3 manage.py runserver 0.0.0.0:8000
    runtime: nvidia