services:
  web:
    build: .
    ports:
      - "8007:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    working_dir: /app/djangoproject
    command:
      - /bin/sh
      - -c
      - |
        export admin_username=theloneadmin
        export admin_password=DjangoIsBellissimo93
        python3 manage.py runserver 0.0.0.0:8000