# Generated by Django 4.2.6 on 2023-10-30 21:31

import diffusers_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='POIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_type', models.CharField(choices=[('ESS', 'establish_shot'), ('ELS', 'eye_level_shot'), ('HIS', 'high_shot'), ('LOS', 'low_shot')], max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=65)),
                ('image', models.ImageField(upload_to=diffusers_api.models.POIImage.poi_image_path)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffusers_api.poi')),
            ],
        ),
    ]
