# Generated by Django 4.2.6 on 2023-11-07 09:30

import diffusers_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='ActionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_type', models.CharField(choices=[('CLS', 'close_shot'), ('MES', 'medium_shot'), ('FUS', 'full_shot'), ('WIS', 'wide_shot'), ('OTS', 'over_the_shoulder')], max_length=3)),
                ('pose_image', models.ImageField(upload_to=diffusers_api.models.ActionImage.image_path)),
                ('mask_image', models.ImageField(upload_to=diffusers_api.models.ActionImage.image_path)),
                ('mask_image_refined', models.ImageField(upload_to=diffusers_api.models.ActionImage.image_path)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffusers_api.action')),
            ],
        ),
    ]
