# Generated by Django 4.2.6 on 2023-11-26 18:09

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0002_action_actionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('model', models.FileField(upload_to=diffusers_api.models.LoraModel.model_path)),
            ],
        ),
    ]
