# Generated by Django 4.2.6 on 2023-11-26 20:23

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0003_loramodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionimage',
            name='subject_face_mask',
            field=models.ImageField(null=True, upload_to=diffusers_api.models.ActionImage.image_path),
        ),
    ]
