# Generated by Django 4.2.6 on 2023-11-27 10:52

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0005_remove_loramodel_model_loramodel_model_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loramodel',
            old_name='model_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(null=True, upload_to=diffusers_api.models.LoraModel.model_path),
        ),
    ]
