# Generated by Django 4.2.6 on 2023-12-03 18:12

import diffusers_api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0006_rename_model_name_loramodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loramodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='actionimage',
            name='subject_face_mask',
            field=models.ImageField(upload_to=diffusers_api.models.ActionImage.image_path),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_trigger',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='poiimage',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='actionimage',
            unique_together={('action', 'shot_type')},
        ),
    ]
