# Generated by Django 4.2.6 on 2023-12-05 19:57

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0007_loramodel_created_at_alter_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionimage',
            name='shot_type',
            field=models.CharField(choices=[('CLS', 'close_shot'), ('MES', 'medium_shot'), ('FUS', 'full_shot'), ('WIS', 'wide_shot')], max_length=3),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
    ]
