# Generated by Django 4.2.6 on 2023-12-17 21:25

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0010_dispatchedloracodes_alter_loramodel_model_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
    ]
