# Generated by Django 4.2.6 on 2023-12-30 17:32

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0012_alter_actionimage_shot_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poiimage',
            name='shot_type',
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
    ]
