# Generated by Django 4.2.6 on 2024-01-26 12:08

import diffusers_api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0014_rename_description_poiimage_prompt_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FECity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
        migrations.CreateModel(
            name='FEPoiMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.IntegerField()),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('overview_image', models.ImageField(upload_to=diffusers_api.models.FEPoiMarker.overview_image_path)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffusers_api.fecity')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffusers_api.poi')),
            ],
        ),
        migrations.CreateModel(
            name='FEArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.IntegerField()),
                ('canvas_x_pos', models.IntegerField()),
                ('canvas_y_pos', models.IntegerField()),
                ('area_image', models.ImageField(upload_to=diffusers_api.models.FEArea.area_image_path)),
                ('connected_areas', models.CharField(max_length=30, validators=[django.core.validators.int_list_validator])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diffusers_api.fecity')),
            ],
        ),
    ]
