# Generated by Django 4.2.6 on 2024-01-26 12:20

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0015_fecity_alter_loramodel_model_path_fepoimarker_fearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
    ]
