# Generated by Django 4.2.6 on 2024-01-26 14:11

import diffusers_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusers_api', '0016_alter_loramodel_model_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fearea',
            name='canvas_x_pos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fearea',
            name='canvas_y_pos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loramodel',
            name='model_path',
            field=models.FileField(upload_to=diffusers_api.models.LoraModel.model_path),
        ),
    ]
